// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ContactSessionInfo;
@class ContactSessionInfo_Builder;
@class DepartInfo;
@class DepartInfo_Builder;
@class GroupInfo;
@class GroupInfo_Builder;
@class GroupVersionInfo;
@class GroupVersionInfo_Builder;
@class InfoNotify;
@class InfoNotify_Builder;
@class IpAddr;
@class IpAddr_Builder;
@class MsgInfo;
@class MsgInfo_Builder;
@class OfflineFileInfo;
@class OfflineFileInfo_Builder;
@class PushResult;
@class PushResult_Builder;
@class PushShieldStatus;
@class PushShieldStatus_Builder;
@class ServerUserStat;
@class ServerUserStat_Builder;
@class ShieldStatus;
@class ShieldStatus_Builder;
@class UnreadInfo;
@class UnreadInfo_Builder;
@class UserInfo;
@class UserInfo_Builder;
@class UserStat;
@class UserStat_Builder;
@class UserTokenInfo;
@class UserTokenInfo_Builder;
typedef enum {
  ServiceIDSidLogin = 1,
  ServiceIDSidBuddyList = 2,
  ServiceIDSidMsg = 3,
  ServiceIDSidGroup = 4,
  ServiceIDSidFile = 5,
  ServiceIDSidSwitchService = 6,
  ServiceIDSidOther = 7,
  ServiceIDSidInternal = 8,
} ServiceID;

BOOL ServiceIDIsValidValue(ServiceID value);

typedef enum {
  LoginCmdIDCidLoginReqMsgserver = 257,
  LoginCmdIDCidLoginResMsgserver = 258,
  LoginCmdIDCidLoginReqUserlogin = 259,
  LoginCmdIDCidLoginResUserlogin = 260,
  LoginCmdIDCidLoginReqLoginout = 261,
  LoginCmdIDCidLoginResLoginout = 262,
  LoginCmdIDCidLoginKickUser = 263,
  LoginCmdIDCidLoginReqDevicetoken = 264,
  LoginCmdIDCidLoginResDevicetoken = 265,
  LoginCmdIDCidLoginReqKickpcclient = 266,
  LoginCmdIDCidLoginResKickpcclient = 267,
  LoginCmdIDCidLoginReqPushShield = 268,
  LoginCmdIDCidLoginResPushShield = 269,
  LoginCmdIDCidLoginReqQueryPushShield = 270,
  LoginCmdIDCidLoginResQueryPushShield = 271,
} LoginCmdID;

BOOL LoginCmdIDIsValidValue(LoginCmdID value);

typedef enum {
  BuddyListCmdIDCidBuddyListRecentContactSessionRequest = 513,
  BuddyListCmdIDCidBuddyListRecentContactSessionResponse = 514,
  BuddyListCmdIDCidBuddyListStatusNotify = 515,
  BuddyListCmdIDCidBuddyListUserInfoRequest = 516,
  BuddyListCmdIDCidBuddyListUserInfoResponse = 517,
  BuddyListCmdIDCidBuddyListRemoveSessionReq = 518,
  BuddyListCmdIDCidBuddyListRemoveSessionRes = 519,
  BuddyListCmdIDCidBuddyListAllUserRequest = 520,
  BuddyListCmdIDCidBuddyListAllUserResponse = 521,
  BuddyListCmdIDCidBuddyListUsersStatusRequest = 522,
  BuddyListCmdIDCidBuddyListUsersStatusResponse = 523,
  BuddyListCmdIDCidBuddyListChangeAvatarRequest = 524,
  BuddyListCmdIDCidBuddyListChangeAvatarResponse = 525,
  BuddyListCmdIDCidBuddyListPcLoginStatusNotify = 526,
  BuddyListCmdIDCidBuddyListRemoveSessionNotify = 527,
  BuddyListCmdIDCidBuddyListDepartmentRequest = 528,
  BuddyListCmdIDCidBuddyListDepartmentResponse = 529,
  BuddyListCmdIDCidBuddyListAvatarChangedNotify = 530,
  BuddyListCmdIDCidBuddyListChangeSignInfoRequest = 531,
  BuddyListCmdIDCidBuddyListChangeSignInfoResponse = 532,
  BuddyListCmdIDCidBuddyListSignInfoChangedNotify = 533,
} BuddyListCmdID;

BOOL BuddyListCmdIDIsValidValue(BuddyListCmdID value);

typedef enum {
  MessageCmdIDCidMsgData = 769,
  MessageCmdIDCidMsgDataAck = 770,
  MessageCmdIDCidMsgReadAck = 771,
  MessageCmdIDCidMsgReadNotify = 772,
  MessageCmdIDCidMsgTimeRequest = 773,
  MessageCmdIDCidMsgTimeResponse = 774,
  MessageCmdIDCidMsgUnreadCntRequest = 775,
  MessageCmdIDCidMsgUnreadCntResponse = 776,
  MessageCmdIDCidMsgListRequest = 777,
  MessageCmdIDCidMsgListResponse = 778,
  MessageCmdIDCidMsgGetLatestMsgIdReq = 779,
  MessageCmdIDCidMsgGetLatestMsgIdRsp = 780,
  MessageCmdIDCidMsgGetByMsgIdReq = 781,
  MessageCmdIDCidMsgGetByMsgIdRes = 782,
} MessageCmdID;

BOOL MessageCmdIDIsValidValue(MessageCmdID value);

typedef enum {
  GroupCmdIDCidGroupNormalListRequest = 1025,
  GroupCmdIDCidGroupNormalListResponse = 1026,
  GroupCmdIDCidGroupInfoRequest = 1027,
  GroupCmdIDCidGroupInfoResponse = 1028,
  GroupCmdIDCidGroupCreateRequest = 1029,
  GroupCmdIDCidGroupCreateResponse = 1030,
  GroupCmdIDCidGroupChangeMemberRequest = 1031,
  GroupCmdIDCidGroupChangeMemberResponse = 1032,
  GroupCmdIDCidGroupShieldGroupRequest = 1033,
  GroupCmdIDCidGroupShieldGroupResponse = 1034,
  GroupCmdIDCidGroupChangeMemberNotify = 1035,
} GroupCmdID;

BOOL GroupCmdIDIsValidValue(GroupCmdID value);

typedef enum {
  FileCmdIDCidFileLoginReq = 1281,
  FileCmdIDCidFileLoginRes = 1282,
  FileCmdIDCidFileState = 1283,
  FileCmdIDCidFilePullDataReq = 1284,
  FileCmdIDCidFilePullDataRsp = 1285,
  FileCmdIDCidFileRequest = 1286,
  FileCmdIDCidFileResponse = 1287,
  FileCmdIDCidFileNotify = 1288,
  FileCmdIDCidFileHasOfflineReq = 1289,
  FileCmdIDCidFileHasOfflineRes = 1290,
  FileCmdIDCidFileAddOfflineReq = 1291,
  FileCmdIDCidFileDelOfflineReq = 1292,
  FileCmdIDCidFileNotifyTouserAck = 1293,
  FileCmdIDCidFileNotifyFromuserAck = 1294,
  FileCmdIDCidFileNotifyMsgserver = 1295,
  FileCmdIDCidFileNotifyDbserver = 1296,
} FileCmdID;

BOOL FileCmdIDIsValidValue(FileCmdID value);

typedef enum {
  SwitchServiceCmdIDCidSwitchP2PCmd = 1537,
} SwitchServiceCmdID;

BOOL SwitchServiceCmdIDIsValidValue(SwitchServiceCmdID value);

typedef enum {
  OtherCmdIDCidOtherHeartbeat = 1793,
  OtherCmdIDCidOtherStopRecvPacket = 1794,
  OtherCmdIDCidOtherValidateReq = 1795,
  OtherCmdIDCidOtherValidateRsp = 1796,
  OtherCmdIDCidOtherGetDeviceTokenReq = 1797,
  OtherCmdIDCidOtherGetDeviceTokenRsp = 1798,
  OtherCmdIDCidOtherRoleSet = 1799,
  OtherCmdIDCidOtherOnlineUserInfo = 1800,
  OtherCmdIDCidOtherMsgServInfo = 1801,
  OtherCmdIDCidOtherUserStatusUpdate = 1802,
  OtherCmdIDCidOtherUserCntUpdate = 1803,
  OtherCmdIDCidOtherServerKickUser = 1805,
  OtherCmdIDCidOtherLoginStatusNotify = 1806,
  OtherCmdIDCidOtherPushToUserReq = 1807,
  OtherCmdIDCidOtherPushToUserRsp = 1808,
  OtherCmdIDCidOtherGetShieldReq = 1809,
  OtherCmdIDCidOtherGetShieldRsp = 1810,
  OtherCmdIDCidOtherFileTransferReq = 1841,
  OtherCmdIDCidOtherFileTransferRsp = 1842,
  OtherCmdIDCidOtherFileServerIpReq = 1843,
  OtherCmdIDCidOtherFileServerIpRsp = 1844,
  OtherCmdIDCidOtherFileDownloadNotify = 1845,
} OtherCmdID;

BOOL OtherCmdIDIsValidValue(OtherCmdID value);

typedef enum {
  ResultTypeRefuseReasonNone = 0,
  ResultTypeRefuseReasonNoMsgServer = 1,
  ResultTypeRefuseReasonMsgServerFull = 2,
  ResultTypeRefuseReasonNoDbServer = 3,
  ResultTypeRefuseReasonNoLoginServer = 4,
  ResultTypeRefuseReasonNoRouteServer = 5,
  ResultTypeRefuseReasonDbValidateFailed = 6,
  ResultTypeRefuseReasonVersionTooOld = 7,
} ResultType;

BOOL ResultTypeIsValidValue(ResultType value);

typedef enum {
  KickReasonTypeKickReasonDuplicateUser = 1,
  KickReasonTypeKickReasonMobileKick = 2,
} KickReasonType;

BOOL KickReasonTypeIsValidValue(KickReasonType value);

typedef enum {
  OnlineListTypeOnlineListTypeFriendList = 1,
} OnlineListType;

BOOL OnlineListTypeIsValidValue(OnlineListType value);

typedef enum {
  UserStatTypeUserStatusOnline = 1,
  UserStatTypeUserStatusOffline = 2,
  UserStatTypeUserStatusLeave = 3,
} UserStatType;

BOOL UserStatTypeIsValidValue(UserStatType value);

typedef enum {
  SessionTypeSessionTypeSingle = 1,
  SessionTypeSessionTypeGroup = 2,
} SessionType;

BOOL SessionTypeIsValidValue(SessionType value);

typedef enum {
  MsgTypeMsgTypeSingleText = 1,
  MsgTypeMsgTypeSingleAudio = 2,
  MsgTypeMsgTypeGroupText = 17,
  MsgTypeMsgTypeGroupAudio = 18,
} MsgType;

BOOL MsgTypeIsValidValue(MsgType value);

typedef enum {
  ClientTypeClientTypeWindows = 1,
  ClientTypeClientTypeMac = 2,
  ClientTypeClientTypeIos = 17,
  ClientTypeClientTypeAndroid = 18,
} ClientType;

BOOL ClientTypeIsValidValue(ClientType value);

typedef enum {
  GroupTypeGroupTypeNormal = 1,
  GroupTypeGroupTypeTmp = 2,
} GroupType;

BOOL GroupTypeIsValidValue(GroupType value);

typedef enum {
  GroupModifyTypeGroupModifyTypeAdd = 1,
  GroupModifyTypeGroupModifyTypeDel = 2,
} GroupModifyType;

BOOL GroupModifyTypeIsValidValue(GroupModifyType value);

typedef enum {
  TransferFileTypeFileTypeOnline = 1,
  TransferFileTypeFileTypeOffline = 2,
} TransferFileType;

BOOL TransferFileTypeIsValidValue(TransferFileType value);

typedef enum {
  TransferTypeFileUpload = 1,
  TransferTypeFileDownload = 2,
} TransferType;

BOOL TransferTypeIsValidValue(TransferType value);

typedef enum {
  ClientFileStateClientFilePeerReady = 0,
  ClientFileStateClientFileCancel = 1,
  ClientFileStateClientFileRefuse = 2,
  ClientFileStateClientFileDone = 3,
} ClientFileState;

BOOL ClientFileStateIsValidValue(ClientFileState value);

typedef enum {
  ClientFileRoleClientRealtimeSender = 1,
  ClientFileRoleClientRealtimeRecver = 2,
  ClientFileRoleClientOfflineUpload = 3,
  ClientFileRoleClientOfflineDownload = 4,
} ClientFileRole;

BOOL ClientFileRoleIsValidValue(ClientFileRole value);

typedef enum {
  FileServerErrorFileServerErrnoOk = 0,
  FileServerErrorFileServerErrnoCreateTaskIdError = 1,
  FileServerErrorFileServerErrnoCreateTaskError = 2,
  FileServerErrorFileServerErrnoLoginInvalidToken = 3,
  FileServerErrorFileServerErrnoInvalidUserForTask = 4,
  FileServerErrorFileServerErrnoPullDataWithInvalidTaskId = 5,
  FileServerErrorFileServerErrnoPullDataIllieageUser = 6,
  FileServerErrorFileServerErrnoPullDataMkdirError = 7,
  FileServerErrorFileServerErrnoPullDataOpenFileError = 8,
  FileServerErrorFileServerErrnoPullDataReadFileHeaderError = 9,
  FileServerErrorFileServerErrnoPullDataAllocMemError = 10,
  FileServerErrorFileServerErrnoPullDataSeekOffsetError = 11,
  FileServerErrorFileServerErrnoPullDataFinished = 12,
} FileServerError;

BOOL FileServerErrorIsValidValue(FileServerError value);

typedef enum {
  SessionStatusTypeSessionStatusOk = 0,
  SessionStatusTypeSessionStatusDelete = 1,
} SessionStatusType;

BOOL SessionStatusTypeIsValidValue(SessionStatusType value);

typedef enum {
  DepartmentStatusTypeDeptStatusOk = 0,
  DepartmentStatusTypeDeptStatusDelete = 1,
} DepartmentStatusType;

BOOL DepartmentStatusTypeIsValidValue(DepartmentStatusType value);

typedef enum {
  FileStatusFileNeedDownload = 1,
  FileStatusFileNeedDisplay = 0,
} FileStatus;

BOOL FileStatusIsValidValue(FileStatus value);


@interface ImBaseDefineRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface IpAddr : PBGeneratedMessage {
@private
  BOOL hasIp_:1;
  BOOL hasPort_:1;
  NSString* ip;
  int32_t port;
}
- (BOOL) hasIp;
- (BOOL) hasPort;
@property (readonly, retain) NSString* ip;
@property (readonly) int32_t port;

+ (IpAddr*) defaultInstance;
- (IpAddr*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IpAddr_Builder*) builder;
+ (IpAddr_Builder*) builder;
+ (IpAddr_Builder*) builderWithPrototype:(IpAddr*) prototype;

+ (IpAddr*) parseFromData:(NSData*) data;
+ (IpAddr*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IpAddr*) parseFromInputStream:(NSInputStream*) input;
+ (IpAddr*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IpAddr*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IpAddr*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IpAddr*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IpAddr_Builder : PBGeneratedMessage_Builder {
@private
  IpAddr* result;
}

- (IpAddr*) defaultInstance;

- (IpAddr_Builder*) clear;
- (IpAddr_Builder*) clone;

- (IpAddr*) build;
- (IpAddr*) buildPartial;

- (IpAddr_Builder*) mergeFrom:(IpAddr*) other;
- (IpAddr_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IpAddr_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIp;
- (NSString*) ip;
- (IpAddr_Builder*) setIp:(NSString*) value;
- (IpAddr_Builder*) clearIp;

- (BOOL) hasPort;
- (int32_t) port;
- (IpAddr_Builder*) setPort:(int32_t) value;
- (IpAddr_Builder*) clearPort;
@end

@interface UserInfo : PBGeneratedMessage {
@private
  BOOL hasUserNickName_:1;
  BOOL hasAvatarUrl_:1;
  BOOL hasEmail_:1;
  BOOL hasUserRealName_:1;
  BOOL hasUserTel_:1;
  BOOL hasUserDomain_:1;
  BOOL hasSignInfo_:1;
  BOOL hasUserId_:1;
  BOOL hasUserGender_:1;
  BOOL hasDepartmentId_:1;
  BOOL hasStatus_:1;
  NSString* userNickName;
  NSString* avatarUrl;
  NSString* email;
  NSString* userRealName;
  NSString* userTel;
  NSString* userDomain;
  NSString* signInfo;
  int32_t userId;
  int32_t userGender;
  int32_t departmentId;
  int32_t status;
}
- (BOOL) hasUserId;
- (BOOL) hasUserGender;
- (BOOL) hasUserNickName;
- (BOOL) hasAvatarUrl;
- (BOOL) hasDepartmentId;
- (BOOL) hasEmail;
- (BOOL) hasUserRealName;
- (BOOL) hasUserTel;
- (BOOL) hasUserDomain;
- (BOOL) hasStatus;
- (BOOL) hasSignInfo;
@property (readonly) int32_t userId;
@property (readonly) int32_t userGender;
@property (readonly, retain) NSString* userNickName;
@property (readonly, retain) NSString* avatarUrl;
@property (readonly) int32_t departmentId;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* userRealName;
@property (readonly, retain) NSString* userTel;
@property (readonly, retain) NSString* userDomain;
@property (readonly) int32_t status;
@property (readonly, retain) NSString* signInfo;

+ (UserInfo*) defaultInstance;
- (UserInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserInfo_Builder*) builder;
+ (UserInfo_Builder*) builder;
+ (UserInfo_Builder*) builderWithPrototype:(UserInfo*) prototype;

+ (UserInfo*) parseFromData:(NSData*) data;
+ (UserInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (UserInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserInfo_Builder : PBGeneratedMessage_Builder {
@private
  UserInfo* result;
}

- (UserInfo*) defaultInstance;

- (UserInfo_Builder*) clear;
- (UserInfo_Builder*) clone;

- (UserInfo*) build;
- (UserInfo*) buildPartial;

- (UserInfo_Builder*) mergeFrom:(UserInfo*) other;
- (UserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserInfo_Builder*) setUserId:(int32_t) value;
- (UserInfo_Builder*) clearUserId;

- (BOOL) hasUserGender;
- (int32_t) userGender;
- (UserInfo_Builder*) setUserGender:(int32_t) value;
- (UserInfo_Builder*) clearUserGender;

- (BOOL) hasUserNickName;
- (NSString*) userNickName;
- (UserInfo_Builder*) setUserNickName:(NSString*) value;
- (UserInfo_Builder*) clearUserNickName;

- (BOOL) hasAvatarUrl;
- (NSString*) avatarUrl;
- (UserInfo_Builder*) setAvatarUrl:(NSString*) value;
- (UserInfo_Builder*) clearAvatarUrl;

- (BOOL) hasDepartmentId;
- (int32_t) departmentId;
- (UserInfo_Builder*) setDepartmentId:(int32_t) value;
- (UserInfo_Builder*) clearDepartmentId;

- (BOOL) hasEmail;
- (NSString*) email;
- (UserInfo_Builder*) setEmail:(NSString*) value;
- (UserInfo_Builder*) clearEmail;

- (BOOL) hasUserRealName;
- (NSString*) userRealName;
- (UserInfo_Builder*) setUserRealName:(NSString*) value;
- (UserInfo_Builder*) clearUserRealName;

- (BOOL) hasUserTel;
- (NSString*) userTel;
- (UserInfo_Builder*) setUserTel:(NSString*) value;
- (UserInfo_Builder*) clearUserTel;

- (BOOL) hasUserDomain;
- (NSString*) userDomain;
- (UserInfo_Builder*) setUserDomain:(NSString*) value;
- (UserInfo_Builder*) clearUserDomain;

- (BOOL) hasStatus;
- (int32_t) status;
- (UserInfo_Builder*) setStatus:(int32_t) value;
- (UserInfo_Builder*) clearStatus;

- (BOOL) hasSignInfo;
- (NSString*) signInfo;
- (UserInfo_Builder*) setSignInfo:(NSString*) value;
- (UserInfo_Builder*) clearSignInfo;
@end

@interface ContactSessionInfo : PBGeneratedMessage {
@private
  BOOL hasLatestMsgData_:1;
  BOOL hasSessionId_:1;
  BOOL hasUpdatedTime_:1;
  BOOL hasLatestMsgId_:1;
  BOOL hasLatestMsgFromUserId_:1;
  BOOL hasSessionType_:1;
  BOOL hasSessionStatus_:1;
  BOOL hasLatestMsgType_:1;
  NSData* latestMsgData;
  int32_t sessionId;
  int32_t updatedTime;
  int32_t latestMsgId;
  int32_t latestMsgFromUserId;
  SessionType sessionType;
  SessionStatusType sessionStatus;
  MsgType latestMsgType;
}
- (BOOL) hasSessionId;
- (BOOL) hasSessionType;
- (BOOL) hasSessionStatus;
- (BOOL) hasUpdatedTime;
- (BOOL) hasLatestMsgId;
- (BOOL) hasLatestMsgData;
- (BOOL) hasLatestMsgType;
- (BOOL) hasLatestMsgFromUserId;
@property (readonly) int32_t sessionId;
@property (readonly) SessionType sessionType;
@property (readonly) SessionStatusType sessionStatus;
@property (readonly) int32_t updatedTime;
@property (readonly) int32_t latestMsgId;
@property (readonly, retain) NSData* latestMsgData;
@property (readonly) MsgType latestMsgType;
@property (readonly) int32_t latestMsgFromUserId;

+ (ContactSessionInfo*) defaultInstance;
- (ContactSessionInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactSessionInfo_Builder*) builder;
+ (ContactSessionInfo_Builder*) builder;
+ (ContactSessionInfo_Builder*) builderWithPrototype:(ContactSessionInfo*) prototype;

+ (ContactSessionInfo*) parseFromData:(NSData*) data;
+ (ContactSessionInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactSessionInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ContactSessionInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ContactSessionInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactSessionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactSessionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactSessionInfo_Builder : PBGeneratedMessage_Builder {
@private
  ContactSessionInfo* result;
}

- (ContactSessionInfo*) defaultInstance;

- (ContactSessionInfo_Builder*) clear;
- (ContactSessionInfo_Builder*) clone;

- (ContactSessionInfo*) build;
- (ContactSessionInfo*) buildPartial;

- (ContactSessionInfo_Builder*) mergeFrom:(ContactSessionInfo*) other;
- (ContactSessionInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactSessionInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (int32_t) sessionId;
- (ContactSessionInfo_Builder*) setSessionId:(int32_t) value;
- (ContactSessionInfo_Builder*) clearSessionId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (ContactSessionInfo_Builder*) setSessionType:(SessionType) value;
- (ContactSessionInfo_Builder*) clearSessionType;

- (BOOL) hasSessionStatus;
- (SessionStatusType) sessionStatus;
- (ContactSessionInfo_Builder*) setSessionStatus:(SessionStatusType) value;
- (ContactSessionInfo_Builder*) clearSessionStatus;

- (BOOL) hasUpdatedTime;
- (int32_t) updatedTime;
- (ContactSessionInfo_Builder*) setUpdatedTime:(int32_t) value;
- (ContactSessionInfo_Builder*) clearUpdatedTime;

- (BOOL) hasLatestMsgId;
- (int32_t) latestMsgId;
- (ContactSessionInfo_Builder*) setLatestMsgId:(int32_t) value;
- (ContactSessionInfo_Builder*) clearLatestMsgId;

- (BOOL) hasLatestMsgData;
- (NSData*) latestMsgData;
- (ContactSessionInfo_Builder*) setLatestMsgData:(NSData*) value;
- (ContactSessionInfo_Builder*) clearLatestMsgData;

- (BOOL) hasLatestMsgType;
- (MsgType) latestMsgType;
- (ContactSessionInfo_Builder*) setLatestMsgType:(MsgType) value;
- (ContactSessionInfo_Builder*) clearLatestMsgType;

- (BOOL) hasLatestMsgFromUserId;
- (int32_t) latestMsgFromUserId;
- (ContactSessionInfo_Builder*) setLatestMsgFromUserId:(int32_t) value;
- (ContactSessionInfo_Builder*) clearLatestMsgFromUserId;
@end

@interface UserStat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasStatus_:1;
  int32_t userId;
  UserStatType status;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
@property (readonly) int32_t userId;
@property (readonly) UserStatType status;

+ (UserStat*) defaultInstance;
- (UserStat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserStat_Builder*) builder;
+ (UserStat_Builder*) builder;
+ (UserStat_Builder*) builderWithPrototype:(UserStat*) prototype;

+ (UserStat*) parseFromData:(NSData*) data;
+ (UserStat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserStat*) parseFromInputStream:(NSInputStream*) input;
+ (UserStat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (UserStat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserStat_Builder : PBGeneratedMessage_Builder {
@private
  UserStat* result;
}

- (UserStat*) defaultInstance;

- (UserStat_Builder*) clear;
- (UserStat_Builder*) clone;

- (UserStat*) build;
- (UserStat*) buildPartial;

- (UserStat_Builder*) mergeFrom:(UserStat*) other;
- (UserStat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserStat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserStat_Builder*) setUserId:(int32_t) value;
- (UserStat_Builder*) clearUserId;

- (BOOL) hasStatus;
- (UserStatType) status;
- (UserStat_Builder*) setStatus:(UserStatType) value;
- (UserStat_Builder*) clearStatus;
@end

@interface ServerUserStat : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasStatus_:1;
  BOOL hasClientType_:1;
  int32_t userId;
  UserStatType status;
  ClientType clientType;
}
- (BOOL) hasUserId;
- (BOOL) hasStatus;
- (BOOL) hasClientType;
@property (readonly) int32_t userId;
@property (readonly) UserStatType status;
@property (readonly) ClientType clientType;

+ (ServerUserStat*) defaultInstance;
- (ServerUserStat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerUserStat_Builder*) builder;
+ (ServerUserStat_Builder*) builder;
+ (ServerUserStat_Builder*) builderWithPrototype:(ServerUserStat*) prototype;

+ (ServerUserStat*) parseFromData:(NSData*) data;
+ (ServerUserStat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserStat*) parseFromInputStream:(NSInputStream*) input;
+ (ServerUserStat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ServerUserStat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServerUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServerUserStat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerUserStat_Builder : PBGeneratedMessage_Builder {
@private
  ServerUserStat* result;
}

- (ServerUserStat*) defaultInstance;

- (ServerUserStat_Builder*) clear;
- (ServerUserStat_Builder*) clone;

- (ServerUserStat*) build;
- (ServerUserStat*) buildPartial;

- (ServerUserStat_Builder*) mergeFrom:(ServerUserStat*) other;
- (ServerUserStat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerUserStat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ServerUserStat_Builder*) setUserId:(int32_t) value;
- (ServerUserStat_Builder*) clearUserId;

- (BOOL) hasStatus;
- (UserStatType) status;
- (ServerUserStat_Builder*) setStatus:(UserStatType) value;
- (ServerUserStat_Builder*) clearStatus;

- (BOOL) hasClientType;
- (ClientType) clientType;
- (ServerUserStat_Builder*) setClientType:(ClientType) value;
- (ServerUserStat_Builder*) clearClientType;
@end

@interface UnreadInfo : PBGeneratedMessage {
@private
  BOOL hasLatestMsgData_:1;
  BOOL hasSessionId_:1;
  BOOL hasUnreadCnt_:1;
  BOOL hasLatestMsgId_:1;
  BOOL hasLatestMsgFromUserId_:1;
  BOOL hasSessionType_:1;
  BOOL hasLatestMsgType_:1;
  NSData* latestMsgData;
  int32_t sessionId;
  int32_t unreadCnt;
  int32_t latestMsgId;
  int32_t latestMsgFromUserId;
  SessionType sessionType;
  MsgType latestMsgType;
}
- (BOOL) hasSessionId;
- (BOOL) hasSessionType;
- (BOOL) hasUnreadCnt;
- (BOOL) hasLatestMsgId;
- (BOOL) hasLatestMsgData;
- (BOOL) hasLatestMsgType;
- (BOOL) hasLatestMsgFromUserId;
@property (readonly) int32_t sessionId;
@property (readonly) SessionType sessionType;
@property (readonly) int32_t unreadCnt;
@property (readonly) int32_t latestMsgId;
@property (readonly, retain) NSData* latestMsgData;
@property (readonly) MsgType latestMsgType;
@property (readonly) int32_t latestMsgFromUserId;

+ (UnreadInfo*) defaultInstance;
- (UnreadInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UnreadInfo_Builder*) builder;
+ (UnreadInfo_Builder*) builder;
+ (UnreadInfo_Builder*) builderWithPrototype:(UnreadInfo*) prototype;

+ (UnreadInfo*) parseFromData:(NSData*) data;
+ (UnreadInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnreadInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UnreadInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (UnreadInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UnreadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UnreadInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UnreadInfo_Builder : PBGeneratedMessage_Builder {
@private
  UnreadInfo* result;
}

- (UnreadInfo*) defaultInstance;

- (UnreadInfo_Builder*) clear;
- (UnreadInfo_Builder*) clone;

- (UnreadInfo*) build;
- (UnreadInfo*) buildPartial;

- (UnreadInfo_Builder*) mergeFrom:(UnreadInfo*) other;
- (UnreadInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UnreadInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (int32_t) sessionId;
- (UnreadInfo_Builder*) setSessionId:(int32_t) value;
- (UnreadInfo_Builder*) clearSessionId;

- (BOOL) hasSessionType;
- (SessionType) sessionType;
- (UnreadInfo_Builder*) setSessionType:(SessionType) value;
- (UnreadInfo_Builder*) clearSessionType;

- (BOOL) hasUnreadCnt;
- (int32_t) unreadCnt;
- (UnreadInfo_Builder*) setUnreadCnt:(int32_t) value;
- (UnreadInfo_Builder*) clearUnreadCnt;

- (BOOL) hasLatestMsgId;
- (int32_t) latestMsgId;
- (UnreadInfo_Builder*) setLatestMsgId:(int32_t) value;
- (UnreadInfo_Builder*) clearLatestMsgId;

- (BOOL) hasLatestMsgData;
- (NSData*) latestMsgData;
- (UnreadInfo_Builder*) setLatestMsgData:(NSData*) value;
- (UnreadInfo_Builder*) clearLatestMsgData;

- (BOOL) hasLatestMsgType;
- (MsgType) latestMsgType;
- (UnreadInfo_Builder*) setLatestMsgType:(MsgType) value;
- (UnreadInfo_Builder*) clearLatestMsgType;

- (BOOL) hasLatestMsgFromUserId;
- (int32_t) latestMsgFromUserId;
- (UnreadInfo_Builder*) setLatestMsgFromUserId:(int32_t) value;
- (UnreadInfo_Builder*) clearLatestMsgFromUserId;
@end

@interface MsgInfo : PBGeneratedMessage {
@private
  BOOL hasMsgData_:1;
  BOOL hasMsgId_:1;
  BOOL hasFromSessionId_:1;
  BOOL hasCreateTime_:1;
  BOOL hasMsgType_:1;
  NSData* msgData;
  int32_t msgId;
  int32_t fromSessionId;
  int32_t createTime;
  MsgType msgType;
}
- (BOOL) hasMsgId;
- (BOOL) hasFromSessionId;
- (BOOL) hasCreateTime;
- (BOOL) hasMsgType;
- (BOOL) hasMsgData;
@property (readonly) int32_t msgId;
@property (readonly) int32_t fromSessionId;
@property (readonly) int32_t createTime;
@property (readonly) MsgType msgType;
@property (readonly, retain) NSData* msgData;

+ (MsgInfo*) defaultInstance;
- (MsgInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MsgInfo_Builder*) builder;
+ (MsgInfo_Builder*) builder;
+ (MsgInfo_Builder*) builderWithPrototype:(MsgInfo*) prototype;

+ (MsgInfo*) parseFromData:(NSData*) data;
+ (MsgInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgInfo*) parseFromInputStream:(NSInputStream*) input;
+ (MsgInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (MsgInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MsgInfo_Builder : PBGeneratedMessage_Builder {
@private
  MsgInfo* result;
}

- (MsgInfo*) defaultInstance;

- (MsgInfo_Builder*) clear;
- (MsgInfo_Builder*) clone;

- (MsgInfo*) build;
- (MsgInfo*) buildPartial;

- (MsgInfo_Builder*) mergeFrom:(MsgInfo*) other;
- (MsgInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MsgInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgId;
- (int32_t) msgId;
- (MsgInfo_Builder*) setMsgId:(int32_t) value;
- (MsgInfo_Builder*) clearMsgId;

- (BOOL) hasFromSessionId;
- (int32_t) fromSessionId;
- (MsgInfo_Builder*) setFromSessionId:(int32_t) value;
- (MsgInfo_Builder*) clearFromSessionId;

- (BOOL) hasCreateTime;
- (int32_t) createTime;
- (MsgInfo_Builder*) setCreateTime:(int32_t) value;
- (MsgInfo_Builder*) clearCreateTime;

- (BOOL) hasMsgType;
- (MsgType) msgType;
- (MsgInfo_Builder*) setMsgType:(MsgType) value;
- (MsgInfo_Builder*) clearMsgType;

- (BOOL) hasMsgData;
- (NSData*) msgData;
- (MsgInfo_Builder*) setMsgData:(NSData*) value;
- (MsgInfo_Builder*) clearMsgData;
@end

@interface GroupVersionInfo : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasVersion_:1;
  int32_t groupId;
  int32_t version;
}
- (BOOL) hasGroupId;
- (BOOL) hasVersion;
@property (readonly) int32_t groupId;
@property (readonly) int32_t version;

+ (GroupVersionInfo*) defaultInstance;
- (GroupVersionInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GroupVersionInfo_Builder*) builder;
+ (GroupVersionInfo_Builder*) builder;
+ (GroupVersionInfo_Builder*) builderWithPrototype:(GroupVersionInfo*) prototype;

+ (GroupVersionInfo*) parseFromData:(NSData*) data;
+ (GroupVersionInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupVersionInfo*) parseFromInputStream:(NSInputStream*) input;
+ (GroupVersionInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (GroupVersionInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupVersionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GroupVersionInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GroupVersionInfo_Builder : PBGeneratedMessage_Builder {
@private
  GroupVersionInfo* result;
}

- (GroupVersionInfo*) defaultInstance;

- (GroupVersionInfo_Builder*) clear;
- (GroupVersionInfo_Builder*) clone;

- (GroupVersionInfo*) build;
- (GroupVersionInfo*) buildPartial;

- (GroupVersionInfo_Builder*) mergeFrom:(GroupVersionInfo*) other;
- (GroupVersionInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GroupVersionInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (int32_t) groupId;
- (GroupVersionInfo_Builder*) setGroupId:(int32_t) value;
- (GroupVersionInfo_Builder*) clearGroupId;

- (BOOL) hasVersion;
- (int32_t) version;
- (GroupVersionInfo_Builder*) setVersion:(int32_t) value;
- (GroupVersionInfo_Builder*) clearVersion;
@end

@interface GroupInfo : PBGeneratedMessage {
@private
  BOOL hasGroupName_:1;
  BOOL hasGroupAvatar_:1;
  BOOL hasGroupId_:1;
  BOOL hasVersion_:1;
  BOOL hasGroupCreatorId_:1;
  BOOL hasShieldStatus_:1;
  BOOL hasGroupType_:1;
  NSString* groupName;
  NSString* groupAvatar;
  int32_t groupId;
  int32_t version;
  int32_t groupCreatorId;
  int32_t shieldStatus;
  GroupType groupType;
  NSMutableArray* mutableGroupMemberListList;
}
- (BOOL) hasGroupId;
- (BOOL) hasVersion;
- (BOOL) hasGroupName;
- (BOOL) hasGroupAvatar;
- (BOOL) hasGroupCreatorId;
- (BOOL) hasGroupType;
- (BOOL) hasShieldStatus;
@property (readonly) int32_t groupId;
@property (readonly) int32_t version;
@property (readonly, retain) NSString* groupName;
@property (readonly, retain) NSString* groupAvatar;
@property (readonly) int32_t groupCreatorId;
@property (readonly) GroupType groupType;
@property (readonly) int32_t shieldStatus;
- (NSArray*) groupMemberListList;
- (int32_t) groupMemberListAtIndex:(int32_t) index;

+ (GroupInfo*) defaultInstance;
- (GroupInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GroupInfo_Builder*) builder;
+ (GroupInfo_Builder*) builder;
+ (GroupInfo_Builder*) builderWithPrototype:(GroupInfo*) prototype;

+ (GroupInfo*) parseFromData:(NSData*) data;
+ (GroupInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupInfo*) parseFromInputStream:(NSInputStream*) input;
+ (GroupInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (GroupInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GroupInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GroupInfo_Builder : PBGeneratedMessage_Builder {
@private
  GroupInfo* result;
}

- (GroupInfo*) defaultInstance;

- (GroupInfo_Builder*) clear;
- (GroupInfo_Builder*) clone;

- (GroupInfo*) build;
- (GroupInfo*) buildPartial;

- (GroupInfo_Builder*) mergeFrom:(GroupInfo*) other;
- (GroupInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GroupInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (int32_t) groupId;
- (GroupInfo_Builder*) setGroupId:(int32_t) value;
- (GroupInfo_Builder*) clearGroupId;

- (BOOL) hasVersion;
- (int32_t) version;
- (GroupInfo_Builder*) setVersion:(int32_t) value;
- (GroupInfo_Builder*) clearVersion;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (GroupInfo_Builder*) setGroupName:(NSString*) value;
- (GroupInfo_Builder*) clearGroupName;

- (BOOL) hasGroupAvatar;
- (NSString*) groupAvatar;
- (GroupInfo_Builder*) setGroupAvatar:(NSString*) value;
- (GroupInfo_Builder*) clearGroupAvatar;

- (BOOL) hasGroupCreatorId;
- (int32_t) groupCreatorId;
- (GroupInfo_Builder*) setGroupCreatorId:(int32_t) value;
- (GroupInfo_Builder*) clearGroupCreatorId;

- (BOOL) hasGroupType;
- (GroupType) groupType;
- (GroupInfo_Builder*) setGroupType:(GroupType) value;
- (GroupInfo_Builder*) clearGroupType;

- (BOOL) hasShieldStatus;
- (int32_t) shieldStatus;
- (GroupInfo_Builder*) setShieldStatus:(int32_t) value;
- (GroupInfo_Builder*) clearShieldStatus;

- (NSArray*) groupMemberListList;
- (int32_t) groupMemberListAtIndex:(int32_t) index;
- (GroupInfo_Builder*) replaceGroupMemberListAtIndex:(int32_t) index with:(int32_t) value;
- (GroupInfo_Builder*) addGroupMemberList:(int32_t) value;
- (GroupInfo_Builder*) addAllGroupMemberList:(NSArray*) values;
- (GroupInfo_Builder*) clearGroupMemberListList;
@end

@interface UserTokenInfo : PBGeneratedMessage {
@private
  BOOL hasToken_:1;
  BOOL hasUserId_:1;
  BOOL hasPushCount_:1;
  BOOL hasPushType_:1;
  BOOL hasUserType_:1;
  NSString* token;
  int32_t userId;
  int32_t pushCount;
  int32_t pushType;
  ClientType userType;
}
- (BOOL) hasUserId;
- (BOOL) hasUserType;
- (BOOL) hasToken;
- (BOOL) hasPushCount;
- (BOOL) hasPushType;
@property (readonly) int32_t userId;
@property (readonly) ClientType userType;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t pushCount;
@property (readonly) int32_t pushType;

+ (UserTokenInfo*) defaultInstance;
- (UserTokenInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserTokenInfo_Builder*) builder;
+ (UserTokenInfo_Builder*) builder;
+ (UserTokenInfo_Builder*) builderWithPrototype:(UserTokenInfo*) prototype;

+ (UserTokenInfo*) parseFromData:(NSData*) data;
+ (UserTokenInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserTokenInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserTokenInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (UserTokenInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserTokenInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserTokenInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserTokenInfo_Builder : PBGeneratedMessage_Builder {
@private
  UserTokenInfo* result;
}

- (UserTokenInfo*) defaultInstance;

- (UserTokenInfo_Builder*) clear;
- (UserTokenInfo_Builder*) clone;

- (UserTokenInfo*) build;
- (UserTokenInfo*) buildPartial;

- (UserTokenInfo_Builder*) mergeFrom:(UserTokenInfo*) other;
- (UserTokenInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserTokenInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (UserTokenInfo_Builder*) setUserId:(int32_t) value;
- (UserTokenInfo_Builder*) clearUserId;

- (BOOL) hasUserType;
- (ClientType) userType;
- (UserTokenInfo_Builder*) setUserType:(ClientType) value;
- (UserTokenInfo_Builder*) clearUserType;

- (BOOL) hasToken;
- (NSString*) token;
- (UserTokenInfo_Builder*) setToken:(NSString*) value;
- (UserTokenInfo_Builder*) clearToken;

- (BOOL) hasPushCount;
- (int32_t) pushCount;
- (UserTokenInfo_Builder*) setPushCount:(int32_t) value;
- (UserTokenInfo_Builder*) clearPushCount;

- (BOOL) hasPushType;
- (int32_t) pushType;
- (UserTokenInfo_Builder*) setPushType:(int32_t) value;
- (UserTokenInfo_Builder*) clearPushType;
@end

@interface PushResult : PBGeneratedMessage {
@private
  BOOL hasUserToken_:1;
  BOOL hasResultCode_:1;
  NSString* userToken;
  int32_t resultCode;
}
- (BOOL) hasUserToken;
- (BOOL) hasResultCode;
@property (readonly, retain) NSString* userToken;
@property (readonly) int32_t resultCode;

+ (PushResult*) defaultInstance;
- (PushResult*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PushResult_Builder*) builder;
+ (PushResult_Builder*) builder;
+ (PushResult_Builder*) builderWithPrototype:(PushResult*) prototype;

+ (PushResult*) parseFromData:(NSData*) data;
+ (PushResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PushResult*) parseFromInputStream:(NSInputStream*) input;
+ (PushResult*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (PushResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PushResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PushResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PushResult_Builder : PBGeneratedMessage_Builder {
@private
  PushResult* result;
}

- (PushResult*) defaultInstance;

- (PushResult_Builder*) clear;
- (PushResult_Builder*) clone;

- (PushResult*) build;
- (PushResult*) buildPartial;

- (PushResult_Builder*) mergeFrom:(PushResult*) other;
- (PushResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PushResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserToken;
- (NSString*) userToken;
- (PushResult_Builder*) setUserToken:(NSString*) value;
- (PushResult_Builder*) clearUserToken;

- (BOOL) hasResultCode;
- (int32_t) resultCode;
- (PushResult_Builder*) setResultCode:(int32_t) value;
- (PushResult_Builder*) clearResultCode;
@end

@interface ShieldStatus : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasGroupId_:1;
  BOOL hasShieldStatus_:1;
  int32_t userId;
  int32_t groupId;
  int32_t shieldStatus;
}
- (BOOL) hasUserId;
- (BOOL) hasGroupId;
- (BOOL) hasShieldStatus;
@property (readonly) int32_t userId;
@property (readonly) int32_t groupId;
@property (readonly) int32_t shieldStatus;

+ (ShieldStatus*) defaultInstance;
- (ShieldStatus*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ShieldStatus_Builder*) builder;
+ (ShieldStatus_Builder*) builder;
+ (ShieldStatus_Builder*) builderWithPrototype:(ShieldStatus*) prototype;

+ (ShieldStatus*) parseFromData:(NSData*) data;
+ (ShieldStatus*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldStatus*) parseFromInputStream:(NSInputStream*) input;
+ (ShieldStatus*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ShieldStatus*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ShieldStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ShieldStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ShieldStatus_Builder : PBGeneratedMessage_Builder {
@private
  ShieldStatus* result;
}

- (ShieldStatus*) defaultInstance;

- (ShieldStatus_Builder*) clear;
- (ShieldStatus_Builder*) clone;

- (ShieldStatus*) build;
- (ShieldStatus*) buildPartial;

- (ShieldStatus_Builder*) mergeFrom:(ShieldStatus*) other;
- (ShieldStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ShieldStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (ShieldStatus_Builder*) setUserId:(int32_t) value;
- (ShieldStatus_Builder*) clearUserId;

- (BOOL) hasGroupId;
- (int32_t) groupId;
- (ShieldStatus_Builder*) setGroupId:(int32_t) value;
- (ShieldStatus_Builder*) clearGroupId;

- (BOOL) hasShieldStatus;
- (int32_t) shieldStatus;
- (ShieldStatus_Builder*) setShieldStatus:(int32_t) value;
- (ShieldStatus_Builder*) clearShieldStatus;
@end

@interface OfflineFileInfo : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasFileName_:1;
  BOOL hasFileMd5_:1;
  BOOL hasFromUserId_:1;
  BOOL hasFileSize_:1;
  BOOL hasStatus_:1;
  NSString* taskId;
  NSString* fileName;
  NSString* fileMd5;
  int32_t fromUserId;
  int32_t fileSize;
  int32_t status;
}
- (BOOL) hasFromUserId;
- (BOOL) hasTaskId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasFileMd5;
- (BOOL) hasStatus;
@property (readonly) int32_t fromUserId;
@property (readonly, retain) NSString* taskId;
@property (readonly, retain) NSString* fileName;
@property (readonly) int32_t fileSize;
@property (readonly, retain) NSString* fileMd5;
@property (readonly) int32_t status;

+ (OfflineFileInfo*) defaultInstance;
- (OfflineFileInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OfflineFileInfo_Builder*) builder;
+ (OfflineFileInfo_Builder*) builder;
+ (OfflineFileInfo_Builder*) builderWithPrototype:(OfflineFileInfo*) prototype;

+ (OfflineFileInfo*) parseFromData:(NSData*) data;
+ (OfflineFileInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineFileInfo*) parseFromInputStream:(NSInputStream*) input;
+ (OfflineFileInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (OfflineFileInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OfflineFileInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OfflineFileInfo_Builder : PBGeneratedMessage_Builder {
@private
  OfflineFileInfo* result;
}

- (OfflineFileInfo*) defaultInstance;

- (OfflineFileInfo_Builder*) clear;
- (OfflineFileInfo_Builder*) clone;

- (OfflineFileInfo*) build;
- (OfflineFileInfo*) buildPartial;

- (OfflineFileInfo_Builder*) mergeFrom:(OfflineFileInfo*) other;
- (OfflineFileInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OfflineFileInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (int32_t) fromUserId;
- (OfflineFileInfo_Builder*) setFromUserId:(int32_t) value;
- (OfflineFileInfo_Builder*) clearFromUserId;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (OfflineFileInfo_Builder*) setTaskId:(NSString*) value;
- (OfflineFileInfo_Builder*) clearTaskId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (OfflineFileInfo_Builder*) setFileName:(NSString*) value;
- (OfflineFileInfo_Builder*) clearFileName;

- (BOOL) hasFileSize;
- (int32_t) fileSize;
- (OfflineFileInfo_Builder*) setFileSize:(int32_t) value;
- (OfflineFileInfo_Builder*) clearFileSize;

- (BOOL) hasFileMd5;
- (NSString*) fileMd5;
- (OfflineFileInfo_Builder*) setFileMd5:(NSString*) value;
- (OfflineFileInfo_Builder*) clearFileMd5;

- (BOOL) hasStatus;
- (int32_t) status;
- (OfflineFileInfo_Builder*) setStatus:(int32_t) value;
- (OfflineFileInfo_Builder*) clearStatus;
@end

@interface DepartInfo : PBGeneratedMessage {
@private
  BOOL hasDeptName_:1;
  BOOL hasDeptId_:1;
  BOOL hasPriority_:1;
  BOOL hasParentDeptId_:1;
  BOOL hasDeptStatus_:1;
  NSString* deptName;
  int32_t deptId;
  int32_t priority;
  int32_t parentDeptId;
  DepartmentStatusType deptStatus;
}
- (BOOL) hasDeptId;
- (BOOL) hasPriority;
- (BOOL) hasDeptName;
- (BOOL) hasParentDeptId;
- (BOOL) hasDeptStatus;
@property (readonly) int32_t deptId;
@property (readonly) int32_t priority;
@property (readonly, retain) NSString* deptName;
@property (readonly) int32_t parentDeptId;
@property (readonly) DepartmentStatusType deptStatus;

+ (DepartInfo*) defaultInstance;
- (DepartInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DepartInfo_Builder*) builder;
+ (DepartInfo_Builder*) builder;
+ (DepartInfo_Builder*) builderWithPrototype:(DepartInfo*) prototype;

+ (DepartInfo*) parseFromData:(NSData*) data;
+ (DepartInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DepartInfo*) parseFromInputStream:(NSInputStream*) input;
+ (DepartInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (DepartInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DepartInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DepartInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DepartInfo_Builder : PBGeneratedMessage_Builder {
@private
  DepartInfo* result;
}

- (DepartInfo*) defaultInstance;

- (DepartInfo_Builder*) clear;
- (DepartInfo_Builder*) clone;

- (DepartInfo*) build;
- (DepartInfo*) buildPartial;

- (DepartInfo_Builder*) mergeFrom:(DepartInfo*) other;
- (DepartInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DepartInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeptId;
- (int32_t) deptId;
- (DepartInfo_Builder*) setDeptId:(int32_t) value;
- (DepartInfo_Builder*) clearDeptId;

- (BOOL) hasPriority;
- (int32_t) priority;
- (DepartInfo_Builder*) setPriority:(int32_t) value;
- (DepartInfo_Builder*) clearPriority;

- (BOOL) hasDeptName;
- (NSString*) deptName;
- (DepartInfo_Builder*) setDeptName:(NSString*) value;
- (DepartInfo_Builder*) clearDeptName;

- (BOOL) hasParentDeptId;
- (int32_t) parentDeptId;
- (DepartInfo_Builder*) setParentDeptId:(int32_t) value;
- (DepartInfo_Builder*) clearParentDeptId;

- (BOOL) hasDeptStatus;
- (DepartmentStatusType) deptStatus;
- (DepartInfo_Builder*) setDeptStatus:(DepartmentStatusType) value;
- (DepartInfo_Builder*) clearDeptStatus;
@end

@interface PushShieldStatus : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasShieldStatus_:1;
  int32_t userId;
  int32_t shieldStatus;
}
- (BOOL) hasUserId;
- (BOOL) hasShieldStatus;
@property (readonly) int32_t userId;
@property (readonly) int32_t shieldStatus;

+ (PushShieldStatus*) defaultInstance;
- (PushShieldStatus*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PushShieldStatus_Builder*) builder;
+ (PushShieldStatus_Builder*) builder;
+ (PushShieldStatus_Builder*) builderWithPrototype:(PushShieldStatus*) prototype;

+ (PushShieldStatus*) parseFromData:(NSData*) data;
+ (PushShieldStatus*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PushShieldStatus*) parseFromInputStream:(NSInputStream*) input;
+ (PushShieldStatus*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (PushShieldStatus*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PushShieldStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PushShieldStatus*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PushShieldStatus_Builder : PBGeneratedMessage_Builder {
@private
  PushShieldStatus* result;
}

- (PushShieldStatus*) defaultInstance;

- (PushShieldStatus_Builder*) clear;
- (PushShieldStatus_Builder*) clone;

- (PushShieldStatus*) build;
- (PushShieldStatus*) buildPartial;

- (PushShieldStatus_Builder*) mergeFrom:(PushShieldStatus*) other;
- (PushShieldStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PushShieldStatus_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (PushShieldStatus_Builder*) setUserId:(int32_t) value;
- (PushShieldStatus_Builder*) clearUserId;

- (BOOL) hasShieldStatus;
- (int32_t) shieldStatus;
- (PushShieldStatus_Builder*) setShieldStatus:(int32_t) value;
- (PushShieldStatus_Builder*) clearShieldStatus;
@end

@interface InfoNotify : PBGeneratedMessage {
@private
  NSMutableArray* mutableOfflineFileListList;
}
- (NSArray*) offlineFileListList;
- (OfflineFileInfo*) offlineFileListAtIndex:(int32_t) index;

+ (InfoNotify*) defaultInstance;
- (InfoNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (InfoNotify_Builder*) builder;
+ (InfoNotify_Builder*) builder;
+ (InfoNotify_Builder*) builderWithPrototype:(InfoNotify*) prototype;

+ (InfoNotify*) parseFromData:(NSData*) data;
+ (InfoNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InfoNotify*) parseFromInputStream:(NSInputStream*) input;
+ (InfoNotify*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (InfoNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (InfoNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (InfoNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface InfoNotify_Builder : PBGeneratedMessage_Builder {
@private
  InfoNotify* result;
}

- (InfoNotify*) defaultInstance;

- (InfoNotify_Builder*) clear;
- (InfoNotify_Builder*) clone;

- (InfoNotify*) build;
- (InfoNotify*) buildPartial;

- (InfoNotify_Builder*) mergeFrom:(InfoNotify*) other;
- (InfoNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (InfoNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) offlineFileListList;
- (OfflineFileInfo*) offlineFileListAtIndex:(int32_t) index;
- (InfoNotify_Builder*) replaceOfflineFileListAtIndex:(int32_t) index with:(OfflineFileInfo*) value;
- (InfoNotify_Builder*) addOfflineFileList:(OfflineFileInfo*) value;
- (InfoNotify_Builder*) addAllOfflineFileList:(NSArray*) values;
- (InfoNotify_Builder*) clearOfflineFileListList;
@end

