// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "ImBaseDefine.pb.h"

@class ContactSessionInfo;
@class ContactSessionInfo_Builder;
@class DepartInfo;
@class DepartInfo_Builder;
@class GroupInfo;
@class GroupInfo_Builder;
@class GroupVersionInfo;
@class GroupVersionInfo_Builder;
@class IMFileAddOfflineReq;
@class IMFileAddOfflineReq_Builder;
@class IMFileDelOfflineReq;
@class IMFileDelOfflineReq_Builder;
@class IMFileHasOfflineReq;
@class IMFileHasOfflineReq_Builder;
@class IMFileHasOfflineRsp;
@class IMFileHasOfflineRsp_Builder;
@class IMFileLoginReq;
@class IMFileLoginReq_Builder;
@class IMFileLoginRsp;
@class IMFileLoginRsp_Builder;
@class IMFileNotify;
@class IMFileNotify_Builder;
@class IMFilePullDataReq;
@class IMFilePullDataReq_Builder;
@class IMFilePullDataRsp;
@class IMFilePullDataRsp_Builder;
@class IMFileReq;
@class IMFileReq_Builder;
@class IMFileRsp;
@class IMFileRsp_Builder;
@class IMFileState;
@class IMFileState_Builder;
@class InfoNotify;
@class InfoNotify_Builder;
@class IpAddr;
@class IpAddr_Builder;
@class MsgInfo;
@class MsgInfo_Builder;
@class OfflineFileInfo;
@class OfflineFileInfo_Builder;
@class PushResult;
@class PushResult_Builder;
@class PushShieldStatus;
@class PushShieldStatus_Builder;
@class ServerUserStat;
@class ServerUserStat_Builder;
@class ShieldStatus;
@class ShieldStatus_Builder;
@class UnreadInfo;
@class UnreadInfo_Builder;
@class UserInfo;
@class UserInfo_Builder;
@class UserStat;
@class UserStat_Builder;
@class UserTokenInfo;
@class UserTokenInfo_Builder;

@interface ImFileRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface IMFileLoginReq : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasUserId_:1;
  BOOL hasFileRole_:1;
  NSString* taskId;
  int32_t userId;
  ClientFileRole fileRole;
}
- (BOOL) hasUserId;
- (BOOL) hasTaskId;
- (BOOL) hasFileRole;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* taskId;
@property (readonly) ClientFileRole fileRole;

+ (IMFileLoginReq*) defaultInstance;
- (IMFileLoginReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileLoginReq_Builder*) builder;
+ (IMFileLoginReq_Builder*) builder;
+ (IMFileLoginReq_Builder*) builderWithPrototype:(IMFileLoginReq*) prototype;

+ (IMFileLoginReq*) parseFromData:(NSData*) data;
+ (IMFileLoginReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileLoginReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileLoginReq*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileLoginReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileLoginReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileLoginReq_Builder : PBGeneratedMessage_Builder {
@private
  IMFileLoginReq* result;
}

- (IMFileLoginReq*) defaultInstance;

- (IMFileLoginReq_Builder*) clear;
- (IMFileLoginReq_Builder*) clone;

- (IMFileLoginReq*) build;
- (IMFileLoginReq*) buildPartial;

- (IMFileLoginReq_Builder*) mergeFrom:(IMFileLoginReq*) other;
- (IMFileLoginReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileLoginReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (IMFileLoginReq_Builder*) setUserId:(int32_t) value;
- (IMFileLoginReq_Builder*) clearUserId;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileLoginReq_Builder*) setTaskId:(NSString*) value;
- (IMFileLoginReq_Builder*) clearTaskId;

- (BOOL) hasFileRole;
- (ClientFileRole) fileRole;
- (IMFileLoginReq_Builder*) setFileRole:(ClientFileRole) value;
- (IMFileLoginReq_Builder*) clearFileRole;
@end

@interface IMFileLoginRsp : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasResultCode_:1;
  NSString* taskId;
  int32_t resultCode;
}
- (BOOL) hasResultCode;
- (BOOL) hasTaskId;
@property (readonly) int32_t resultCode;
@property (readonly, retain) NSString* taskId;

+ (IMFileLoginRsp*) defaultInstance;
- (IMFileLoginRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileLoginRsp_Builder*) builder;
+ (IMFileLoginRsp_Builder*) builder;
+ (IMFileLoginRsp_Builder*) builderWithPrototype:(IMFileLoginRsp*) prototype;

+ (IMFileLoginRsp*) parseFromData:(NSData*) data;
+ (IMFileLoginRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileLoginRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileLoginRsp*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileLoginRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileLoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileLoginRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileLoginRsp_Builder : PBGeneratedMessage_Builder {
@private
  IMFileLoginRsp* result;
}

- (IMFileLoginRsp*) defaultInstance;

- (IMFileLoginRsp_Builder*) clear;
- (IMFileLoginRsp_Builder*) clone;

- (IMFileLoginRsp*) build;
- (IMFileLoginRsp*) buildPartial;

- (IMFileLoginRsp_Builder*) mergeFrom:(IMFileLoginRsp*) other;
- (IMFileLoginRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileLoginRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResultCode;
- (int32_t) resultCode;
- (IMFileLoginRsp_Builder*) setResultCode:(int32_t) value;
- (IMFileLoginRsp_Builder*) clearResultCode;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileLoginRsp_Builder*) setTaskId:(NSString*) value;
- (IMFileLoginRsp_Builder*) clearTaskId;
@end

@interface IMFileState : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasUserId_:1;
  BOOL hasState_:1;
  BOOL hasTtype_:1;
  NSString* taskId;
  int32_t userId;
  ClientFileState state;
  TransferType ttype;
}
- (BOOL) hasState;
- (BOOL) hasTtype;
- (BOOL) hasTaskId;
- (BOOL) hasUserId;
@property (readonly) ClientFileState state;
@property (readonly) TransferType ttype;
@property (readonly, retain) NSString* taskId;
@property (readonly) int32_t userId;

+ (IMFileState*) defaultInstance;
- (IMFileState*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileState_Builder*) builder;
+ (IMFileState_Builder*) builder;
+ (IMFileState_Builder*) builderWithPrototype:(IMFileState*) prototype;

+ (IMFileState*) parseFromData:(NSData*) data;
+ (IMFileState*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileState*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileState*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileState*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileState*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileState*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileState_Builder : PBGeneratedMessage_Builder {
@private
  IMFileState* result;
}

- (IMFileState*) defaultInstance;

- (IMFileState_Builder*) clear;
- (IMFileState_Builder*) clone;

- (IMFileState*) build;
- (IMFileState*) buildPartial;

- (IMFileState_Builder*) mergeFrom:(IMFileState*) other;
- (IMFileState_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileState_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasState;
- (ClientFileState) state;
- (IMFileState_Builder*) setState:(ClientFileState) value;
- (IMFileState_Builder*) clearState;

- (BOOL) hasTtype;
- (TransferType) ttype;
- (IMFileState_Builder*) setTtype:(TransferType) value;
- (IMFileState_Builder*) clearTtype;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileState_Builder*) setTaskId:(NSString*) value;
- (IMFileState_Builder*) clearTaskId;

- (BOOL) hasUserId;
- (int32_t) userId;
- (IMFileState_Builder*) setUserId:(int32_t) value;
- (IMFileState_Builder*) clearUserId;
@end

@interface IMFilePullDataReq : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasUserId_:1;
  BOOL hasOffset_:1;
  BOOL hasDataSize_:1;
  BOOL hasTransMode_:1;
  NSString* taskId;
  int32_t userId;
  int32_t offset;
  int32_t dataSize;
  TransferFileType transMode;
}
- (BOOL) hasTaskId;
- (BOOL) hasUserId;
- (BOOL) hasTransMode;
- (BOOL) hasOffset;
- (BOOL) hasDataSize;
@property (readonly, retain) NSString* taskId;
@property (readonly) int32_t userId;
@property (readonly) TransferFileType transMode;
@property (readonly) int32_t offset;
@property (readonly) int32_t dataSize;

+ (IMFilePullDataReq*) defaultInstance;
- (IMFilePullDataReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFilePullDataReq_Builder*) builder;
+ (IMFilePullDataReq_Builder*) builder;
+ (IMFilePullDataReq_Builder*) builderWithPrototype:(IMFilePullDataReq*) prototype;

+ (IMFilePullDataReq*) parseFromData:(NSData*) data;
+ (IMFilePullDataReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFilePullDataReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFilePullDataReq*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFilePullDataReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFilePullDataReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFilePullDataReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFilePullDataReq_Builder : PBGeneratedMessage_Builder {
@private
  IMFilePullDataReq* result;
}

- (IMFilePullDataReq*) defaultInstance;

- (IMFilePullDataReq_Builder*) clear;
- (IMFilePullDataReq_Builder*) clone;

- (IMFilePullDataReq*) build;
- (IMFilePullDataReq*) buildPartial;

- (IMFilePullDataReq_Builder*) mergeFrom:(IMFilePullDataReq*) other;
- (IMFilePullDataReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFilePullDataReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFilePullDataReq_Builder*) setTaskId:(NSString*) value;
- (IMFilePullDataReq_Builder*) clearTaskId;

- (BOOL) hasUserId;
- (int32_t) userId;
- (IMFilePullDataReq_Builder*) setUserId:(int32_t) value;
- (IMFilePullDataReq_Builder*) clearUserId;

- (BOOL) hasTransMode;
- (TransferFileType) transMode;
- (IMFilePullDataReq_Builder*) setTransMode:(TransferFileType) value;
- (IMFilePullDataReq_Builder*) clearTransMode;

- (BOOL) hasOffset;
- (int32_t) offset;
- (IMFilePullDataReq_Builder*) setOffset:(int32_t) value;
- (IMFilePullDataReq_Builder*) clearOffset;

- (BOOL) hasDataSize;
- (int32_t) dataSize;
- (IMFilePullDataReq_Builder*) setDataSize:(int32_t) value;
- (IMFilePullDataReq_Builder*) clearDataSize;
@end

@interface IMFilePullDataRsp : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasFileData_:1;
  BOOL hasResultCode_:1;
  BOOL hasUserId_:1;
  BOOL hasOffset_:1;
  NSString* taskId;
  NSData* fileData;
  int32_t resultCode;
  int32_t userId;
  int32_t offset;
}
- (BOOL) hasResultCode;
- (BOOL) hasTaskId;
- (BOOL) hasUserId;
- (BOOL) hasOffset;
- (BOOL) hasFileData;
@property (readonly) int32_t resultCode;
@property (readonly, retain) NSString* taskId;
@property (readonly) int32_t userId;
@property (readonly) int32_t offset;
@property (readonly, retain) NSData* fileData;

+ (IMFilePullDataRsp*) defaultInstance;
- (IMFilePullDataRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFilePullDataRsp_Builder*) builder;
+ (IMFilePullDataRsp_Builder*) builder;
+ (IMFilePullDataRsp_Builder*) builderWithPrototype:(IMFilePullDataRsp*) prototype;

+ (IMFilePullDataRsp*) parseFromData:(NSData*) data;
+ (IMFilePullDataRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFilePullDataRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMFilePullDataRsp*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFilePullDataRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFilePullDataRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFilePullDataRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFilePullDataRsp_Builder : PBGeneratedMessage_Builder {
@private
  IMFilePullDataRsp* result;
}

- (IMFilePullDataRsp*) defaultInstance;

- (IMFilePullDataRsp_Builder*) clear;
- (IMFilePullDataRsp_Builder*) clone;

- (IMFilePullDataRsp*) build;
- (IMFilePullDataRsp*) buildPartial;

- (IMFilePullDataRsp_Builder*) mergeFrom:(IMFilePullDataRsp*) other;
- (IMFilePullDataRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFilePullDataRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResultCode;
- (int32_t) resultCode;
- (IMFilePullDataRsp_Builder*) setResultCode:(int32_t) value;
- (IMFilePullDataRsp_Builder*) clearResultCode;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFilePullDataRsp_Builder*) setTaskId:(NSString*) value;
- (IMFilePullDataRsp_Builder*) clearTaskId;

- (BOOL) hasUserId;
- (int32_t) userId;
- (IMFilePullDataRsp_Builder*) setUserId:(int32_t) value;
- (IMFilePullDataRsp_Builder*) clearUserId;

- (BOOL) hasOffset;
- (int32_t) offset;
- (IMFilePullDataRsp_Builder*) setOffset:(int32_t) value;
- (IMFilePullDataRsp_Builder*) clearOffset;

- (BOOL) hasFileData;
- (NSData*) fileData;
- (IMFilePullDataRsp_Builder*) setFileData:(NSData*) value;
- (IMFilePullDataRsp_Builder*) clearFileData;
@end

@interface IMFileReq : PBGeneratedMessage {
@private
  BOOL hasFileName_:1;
  BOOL hasFileMd5_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileSize_:1;
  BOOL hasTransMode_:1;
  NSString* fileName;
  NSString* fileMd5;
  int32_t fromUserId;
  int32_t toUserId;
  int32_t fileSize;
  TransferFileType transMode;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasTransMode;
- (BOOL) hasFileMd5;
@property (readonly) int32_t fromUserId;
@property (readonly) int32_t toUserId;
@property (readonly, retain) NSString* fileName;
@property (readonly) int32_t fileSize;
@property (readonly) TransferFileType transMode;
@property (readonly, retain) NSString* fileMd5;

+ (IMFileReq*) defaultInstance;
- (IMFileReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileReq_Builder*) builder;
+ (IMFileReq_Builder*) builder;
+ (IMFileReq_Builder*) builderWithPrototype:(IMFileReq*) prototype;

+ (IMFileReq*) parseFromData:(NSData*) data;
+ (IMFileReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileReq*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileReq_Builder : PBGeneratedMessage_Builder {
@private
  IMFileReq* result;
}

- (IMFileReq*) defaultInstance;

- (IMFileReq_Builder*) clear;
- (IMFileReq_Builder*) clone;

- (IMFileReq*) build;
- (IMFileReq*) buildPartial;

- (IMFileReq_Builder*) mergeFrom:(IMFileReq*) other;
- (IMFileReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (int32_t) fromUserId;
- (IMFileReq_Builder*) setFromUserId:(int32_t) value;
- (IMFileReq_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (int32_t) toUserId;
- (IMFileReq_Builder*) setToUserId:(int32_t) value;
- (IMFileReq_Builder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileReq_Builder*) setFileName:(NSString*) value;
- (IMFileReq_Builder*) clearFileName;

- (BOOL) hasFileSize;
- (int32_t) fileSize;
- (IMFileReq_Builder*) setFileSize:(int32_t) value;
- (IMFileReq_Builder*) clearFileSize;

- (BOOL) hasTransMode;
- (TransferFileType) transMode;
- (IMFileReq_Builder*) setTransMode:(TransferFileType) value;
- (IMFileReq_Builder*) clearTransMode;

- (BOOL) hasFileMd5;
- (NSString*) fileMd5;
- (IMFileReq_Builder*) setFileMd5:(NSString*) value;
- (IMFileReq_Builder*) clearFileMd5;
@end

@interface IMFileRsp : PBGeneratedMessage {
@private
  BOOL hasFileName_:1;
  BOOL hasTaskId_:1;
  BOOL hasResultCode_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasTransMode_:1;
  NSString* fileName;
  NSString* taskId;
  int32_t resultCode;
  int32_t fromUserId;
  int32_t toUserId;
  TransferFileType transMode;
  NSMutableArray* mutableIpAddrListList;
}
- (BOOL) hasResultCode;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasTaskId;
- (BOOL) hasTransMode;
@property (readonly) int32_t resultCode;
@property (readonly) int32_t fromUserId;
@property (readonly) int32_t toUserId;
@property (readonly, retain) NSString* fileName;
@property (readonly, retain) NSString* taskId;
@property (readonly) TransferFileType transMode;
- (NSArray*) ipAddrListList;
- (IpAddr*) ipAddrListAtIndex:(int32_t) index;

+ (IMFileRsp*) defaultInstance;
- (IMFileRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileRsp_Builder*) builder;
+ (IMFileRsp_Builder*) builder;
+ (IMFileRsp_Builder*) builderWithPrototype:(IMFileRsp*) prototype;

+ (IMFileRsp*) parseFromData:(NSData*) data;
+ (IMFileRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileRsp*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileRsp_Builder : PBGeneratedMessage_Builder {
@private
  IMFileRsp* result;
}

- (IMFileRsp*) defaultInstance;

- (IMFileRsp_Builder*) clear;
- (IMFileRsp_Builder*) clone;

- (IMFileRsp*) build;
- (IMFileRsp*) buildPartial;

- (IMFileRsp_Builder*) mergeFrom:(IMFileRsp*) other;
- (IMFileRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResultCode;
- (int32_t) resultCode;
- (IMFileRsp_Builder*) setResultCode:(int32_t) value;
- (IMFileRsp_Builder*) clearResultCode;

- (BOOL) hasFromUserId;
- (int32_t) fromUserId;
- (IMFileRsp_Builder*) setFromUserId:(int32_t) value;
- (IMFileRsp_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (int32_t) toUserId;
- (IMFileRsp_Builder*) setToUserId:(int32_t) value;
- (IMFileRsp_Builder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileRsp_Builder*) setFileName:(NSString*) value;
- (IMFileRsp_Builder*) clearFileName;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileRsp_Builder*) setTaskId:(NSString*) value;
- (IMFileRsp_Builder*) clearTaskId;

- (NSArray*) ipAddrListList;
- (IpAddr*) ipAddrListAtIndex:(int32_t) index;
- (IMFileRsp_Builder*) replaceIpAddrListAtIndex:(int32_t) index with:(IpAddr*) value;
- (IMFileRsp_Builder*) addIpAddrList:(IpAddr*) value;
- (IMFileRsp_Builder*) addAllIpAddrList:(NSArray*) values;
- (IMFileRsp_Builder*) clearIpAddrListList;

- (BOOL) hasTransMode;
- (TransferFileType) transMode;
- (IMFileRsp_Builder*) setTransMode:(TransferFileType) value;
- (IMFileRsp_Builder*) clearTransMode;
@end

@interface IMFileNotify : PBGeneratedMessage {
@private
  BOOL hasFileName_:1;
  BOOL hasTaskId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileSize_:1;
  BOOL hasOfflineReady_:1;
  BOOL hasTransMode_:1;
  NSString* fileName;
  NSString* taskId;
  int32_t fromUserId;
  int32_t toUserId;
  int32_t fileSize;
  int32_t offlineReady;
  TransferFileType transMode;
  NSMutableArray* mutableIpAddrListList;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasTaskId;
- (BOOL) hasTransMode;
- (BOOL) hasOfflineReady;
@property (readonly) int32_t fromUserId;
@property (readonly) int32_t toUserId;
@property (readonly, retain) NSString* fileName;
@property (readonly) int32_t fileSize;
@property (readonly, retain) NSString* taskId;
@property (readonly) TransferFileType transMode;
@property (readonly) int32_t offlineReady;
- (NSArray*) ipAddrListList;
- (IpAddr*) ipAddrListAtIndex:(int32_t) index;

+ (IMFileNotify*) defaultInstance;
- (IMFileNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileNotify_Builder*) builder;
+ (IMFileNotify_Builder*) builder;
+ (IMFileNotify_Builder*) builderWithPrototype:(IMFileNotify*) prototype;

+ (IMFileNotify*) parseFromData:(NSData*) data;
+ (IMFileNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileNotify*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileNotify*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileNotify_Builder : PBGeneratedMessage_Builder {
@private
  IMFileNotify* result;
}

- (IMFileNotify*) defaultInstance;

- (IMFileNotify_Builder*) clear;
- (IMFileNotify_Builder*) clone;

- (IMFileNotify*) build;
- (IMFileNotify*) buildPartial;

- (IMFileNotify_Builder*) mergeFrom:(IMFileNotify*) other;
- (IMFileNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (int32_t) fromUserId;
- (IMFileNotify_Builder*) setFromUserId:(int32_t) value;
- (IMFileNotify_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (int32_t) toUserId;
- (IMFileNotify_Builder*) setToUserId:(int32_t) value;
- (IMFileNotify_Builder*) clearToUserId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileNotify_Builder*) setFileName:(NSString*) value;
- (IMFileNotify_Builder*) clearFileName;

- (BOOL) hasFileSize;
- (int32_t) fileSize;
- (IMFileNotify_Builder*) setFileSize:(int32_t) value;
- (IMFileNotify_Builder*) clearFileSize;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileNotify_Builder*) setTaskId:(NSString*) value;
- (IMFileNotify_Builder*) clearTaskId;

- (NSArray*) ipAddrListList;
- (IpAddr*) ipAddrListAtIndex:(int32_t) index;
- (IMFileNotify_Builder*) replaceIpAddrListAtIndex:(int32_t) index with:(IpAddr*) value;
- (IMFileNotify_Builder*) addIpAddrList:(IpAddr*) value;
- (IMFileNotify_Builder*) addAllIpAddrList:(NSArray*) values;
- (IMFileNotify_Builder*) clearIpAddrListList;

- (BOOL) hasTransMode;
- (TransferFileType) transMode;
- (IMFileNotify_Builder*) setTransMode:(TransferFileType) value;
- (IMFileNotify_Builder*) clearTransMode;

- (BOOL) hasOfflineReady;
- (int32_t) offlineReady;
- (IMFileNotify_Builder*) setOfflineReady:(int32_t) value;
- (IMFileNotify_Builder*) clearOfflineReady;
@end

@interface IMFileHasOfflineReq : PBGeneratedMessage {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  int32_t userId;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) int32_t userId;
@property (readonly, retain) NSData* attachData;

+ (IMFileHasOfflineReq*) defaultInstance;
- (IMFileHasOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileHasOfflineReq_Builder*) builder;
+ (IMFileHasOfflineReq_Builder*) builder;
+ (IMFileHasOfflineReq_Builder*) builderWithPrototype:(IMFileHasOfflineReq*) prototype;

+ (IMFileHasOfflineReq*) parseFromData:(NSData*) data;
+ (IMFileHasOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileHasOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileHasOfflineReq*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileHasOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileHasOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileHasOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileHasOfflineReq_Builder : PBGeneratedMessage_Builder {
@private
  IMFileHasOfflineReq* result;
}

- (IMFileHasOfflineReq*) defaultInstance;

- (IMFileHasOfflineReq_Builder*) clear;
- (IMFileHasOfflineReq_Builder*) clone;

- (IMFileHasOfflineReq*) build;
- (IMFileHasOfflineReq*) buildPartial;

- (IMFileHasOfflineReq_Builder*) mergeFrom:(IMFileHasOfflineReq*) other;
- (IMFileHasOfflineReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileHasOfflineReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (IMFileHasOfflineReq_Builder*) setUserId:(int32_t) value;
- (IMFileHasOfflineReq_Builder*) clearUserId;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMFileHasOfflineReq_Builder*) setAttachData:(NSData*) value;
- (IMFileHasOfflineReq_Builder*) clearAttachData;
@end

@interface IMFileHasOfflineRsp : PBGeneratedMessage {
@private
  BOOL hasAttachData_:1;
  BOOL hasUserId_:1;
  NSData* attachData;
  int32_t userId;
  NSMutableArray* mutableOfflineFileListList;
  NSMutableArray* mutableIpAddrListList;
}
- (BOOL) hasUserId;
- (BOOL) hasAttachData;
@property (readonly) int32_t userId;
@property (readonly, retain) NSData* attachData;
- (NSArray*) offlineFileListList;
- (OfflineFileInfo*) offlineFileListAtIndex:(int32_t) index;
- (NSArray*) ipAddrListList;
- (IpAddr*) ipAddrListAtIndex:(int32_t) index;

+ (IMFileHasOfflineRsp*) defaultInstance;
- (IMFileHasOfflineRsp*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileHasOfflineRsp_Builder*) builder;
+ (IMFileHasOfflineRsp_Builder*) builder;
+ (IMFileHasOfflineRsp_Builder*) builderWithPrototype:(IMFileHasOfflineRsp*) prototype;

+ (IMFileHasOfflineRsp*) parseFromData:(NSData*) data;
+ (IMFileHasOfflineRsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileHasOfflineRsp*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileHasOfflineRsp*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileHasOfflineRsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileHasOfflineRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileHasOfflineRsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileHasOfflineRsp_Builder : PBGeneratedMessage_Builder {
@private
  IMFileHasOfflineRsp* result;
}

- (IMFileHasOfflineRsp*) defaultInstance;

- (IMFileHasOfflineRsp_Builder*) clear;
- (IMFileHasOfflineRsp_Builder*) clone;

- (IMFileHasOfflineRsp*) build;
- (IMFileHasOfflineRsp*) buildPartial;

- (IMFileHasOfflineRsp_Builder*) mergeFrom:(IMFileHasOfflineRsp*) other;
- (IMFileHasOfflineRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileHasOfflineRsp_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (IMFileHasOfflineRsp_Builder*) setUserId:(int32_t) value;
- (IMFileHasOfflineRsp_Builder*) clearUserId;

- (NSArray*) offlineFileListList;
- (OfflineFileInfo*) offlineFileListAtIndex:(int32_t) index;
- (IMFileHasOfflineRsp_Builder*) replaceOfflineFileListAtIndex:(int32_t) index with:(OfflineFileInfo*) value;
- (IMFileHasOfflineRsp_Builder*) addOfflineFileList:(OfflineFileInfo*) value;
- (IMFileHasOfflineRsp_Builder*) addAllOfflineFileList:(NSArray*) values;
- (IMFileHasOfflineRsp_Builder*) clearOfflineFileListList;

- (NSArray*) ipAddrListList;
- (IpAddr*) ipAddrListAtIndex:(int32_t) index;
- (IMFileHasOfflineRsp_Builder*) replaceIpAddrListAtIndex:(int32_t) index with:(IpAddr*) value;
- (IMFileHasOfflineRsp_Builder*) addIpAddrList:(IpAddr*) value;
- (IMFileHasOfflineRsp_Builder*) addAllIpAddrList:(NSArray*) values;
- (IMFileHasOfflineRsp_Builder*) clearIpAddrListList;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMFileHasOfflineRsp_Builder*) setAttachData:(NSData*) value;
- (IMFileHasOfflineRsp_Builder*) clearAttachData;
@end

@interface IMFileAddOfflineReq : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasFileName_:1;
  BOOL hasFileMd5_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileSize_:1;
  BOOL hasStatus_:1;
  NSString* taskId;
  NSString* fileName;
  NSString* fileMd5;
  int32_t fromUserId;
  int32_t toUserId;
  int32_t fileSize;
  int32_t status;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasTaskId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
- (BOOL) hasFileMd5;
- (BOOL) hasStatus;
@property (readonly) int32_t fromUserId;
@property (readonly) int32_t toUserId;
@property (readonly, retain) NSString* taskId;
@property (readonly, retain) NSString* fileName;
@property (readonly) int32_t fileSize;
@property (readonly, retain) NSString* fileMd5;
@property (readonly) int32_t status;

+ (IMFileAddOfflineReq*) defaultInstance;
- (IMFileAddOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileAddOfflineReq_Builder*) builder;
+ (IMFileAddOfflineReq_Builder*) builder;
+ (IMFileAddOfflineReq_Builder*) builderWithPrototype:(IMFileAddOfflineReq*) prototype;

+ (IMFileAddOfflineReq*) parseFromData:(NSData*) data;
+ (IMFileAddOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileAddOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileAddOfflineReq*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileAddOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileAddOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileAddOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileAddOfflineReq_Builder : PBGeneratedMessage_Builder {
@private
  IMFileAddOfflineReq* result;
}

- (IMFileAddOfflineReq*) defaultInstance;

- (IMFileAddOfflineReq_Builder*) clear;
- (IMFileAddOfflineReq_Builder*) clone;

- (IMFileAddOfflineReq*) build;
- (IMFileAddOfflineReq*) buildPartial;

- (IMFileAddOfflineReq_Builder*) mergeFrom:(IMFileAddOfflineReq*) other;
- (IMFileAddOfflineReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileAddOfflineReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (int32_t) fromUserId;
- (IMFileAddOfflineReq_Builder*) setFromUserId:(int32_t) value;
- (IMFileAddOfflineReq_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (int32_t) toUserId;
- (IMFileAddOfflineReq_Builder*) setToUserId:(int32_t) value;
- (IMFileAddOfflineReq_Builder*) clearToUserId;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileAddOfflineReq_Builder*) setTaskId:(NSString*) value;
- (IMFileAddOfflineReq_Builder*) clearTaskId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileAddOfflineReq_Builder*) setFileName:(NSString*) value;
- (IMFileAddOfflineReq_Builder*) clearFileName;

- (BOOL) hasFileSize;
- (int32_t) fileSize;
- (IMFileAddOfflineReq_Builder*) setFileSize:(int32_t) value;
- (IMFileAddOfflineReq_Builder*) clearFileSize;

- (BOOL) hasFileMd5;
- (NSString*) fileMd5;
- (IMFileAddOfflineReq_Builder*) setFileMd5:(NSString*) value;
- (IMFileAddOfflineReq_Builder*) clearFileMd5;

- (BOOL) hasStatus;
- (int32_t) status;
- (IMFileAddOfflineReq_Builder*) setStatus:(int32_t) value;
- (IMFileAddOfflineReq_Builder*) clearStatus;
@end

@interface IMFileDelOfflineReq : PBGeneratedMessage {
@private
  BOOL hasTaskId_:1;
  BOOL hasFileName_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasFileSize_:1;
  NSString* taskId;
  NSString* fileName;
  int32_t fromUserId;
  int32_t toUserId;
  int32_t fileSize;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasTaskId;
- (BOOL) hasFileName;
- (BOOL) hasFileSize;
@property (readonly) int32_t fromUserId;
@property (readonly) int32_t toUserId;
@property (readonly, retain) NSString* taskId;
@property (readonly, retain) NSString* fileName;
@property (readonly) int32_t fileSize;

+ (IMFileDelOfflineReq*) defaultInstance;
- (IMFileDelOfflineReq*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMFileDelOfflineReq_Builder*) builder;
+ (IMFileDelOfflineReq_Builder*) builder;
+ (IMFileDelOfflineReq_Builder*) builderWithPrototype:(IMFileDelOfflineReq*) prototype;

+ (IMFileDelOfflineReq*) parseFromData:(NSData*) data;
+ (IMFileDelOfflineReq*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileDelOfflineReq*) parseFromInputStream:(NSInputStream*) input;
+ (IMFileDelOfflineReq*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (IMFileDelOfflineReq*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMFileDelOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMFileDelOfflineReq*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMFileDelOfflineReq_Builder : PBGeneratedMessage_Builder {
@private
  IMFileDelOfflineReq* result;
}

- (IMFileDelOfflineReq*) defaultInstance;

- (IMFileDelOfflineReq_Builder*) clear;
- (IMFileDelOfflineReq_Builder*) clone;

- (IMFileDelOfflineReq*) build;
- (IMFileDelOfflineReq*) buildPartial;

- (IMFileDelOfflineReq_Builder*) mergeFrom:(IMFileDelOfflineReq*) other;
- (IMFileDelOfflineReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMFileDelOfflineReq_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (int32_t) fromUserId;
- (IMFileDelOfflineReq_Builder*) setFromUserId:(int32_t) value;
- (IMFileDelOfflineReq_Builder*) clearFromUserId;

- (BOOL) hasToUserId;
- (int32_t) toUserId;
- (IMFileDelOfflineReq_Builder*) setToUserId:(int32_t) value;
- (IMFileDelOfflineReq_Builder*) clearToUserId;

- (BOOL) hasTaskId;
- (NSString*) taskId;
- (IMFileDelOfflineReq_Builder*) setTaskId:(NSString*) value;
- (IMFileDelOfflineReq_Builder*) clearTaskId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (IMFileDelOfflineReq_Builder*) setFileName:(NSString*) value;
- (IMFileDelOfflineReq_Builder*) clearFileName;

- (BOOL) hasFileSize;
- (int32_t) fileSize;
- (IMFileDelOfflineReq_Builder*) setFileSize:(int32_t) value;
- (IMFileDelOfflineReq_Builder*) clearFileSize;
@end

